### ISSUE TITLE
C 

### ISSUE THREAD

**Issue by Akshaybhandarkar123** [Akshaybhandarkar123/github-slideshow#2]
#include<stdio.h>
Main()
{
Int team1,team2;
Char[50]
Printf(enter team1 name");
Scanf("%d",&team1");
Printf(enter team2 name");
Scanf("%s",&team2")
If(team1=100)
{
Printf("team 1 win");
}
else
{
Printf("team2 is win");
}
}

**Comment by icarus-27** [comment]
Hi

**Comment by Akshaybhandarkar123** [comment]
Hi
